// Code generated by entc, DO NOT EDIT.

package guild

const (
	// Label holds the string label denoting the guild type in the database.
	Label = "guild"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMessage holds the string denoting the message vertex property in the database.
	FieldMessage = "message"
	// FieldCategories holds the string denoting the categories vertex property in the database.
	FieldCategories = "categories"

	// Table holds the table name of the guild in the database.
	Table = "guilds"
)

// Columns holds all SQL columns are guild fields.
var Columns = []string{
	FieldID,
	FieldMessage,
	FieldCategories,
}
