// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Guild is the predicate function for guild builders.
type Guild func(*sql.Selector)
